math.randomseed(os.time())

local home = os.getenv("HOME")
local wallpaperdir = home .. "/Pictures/Wallpapers"
local hyprpaper_conf = home .. "/.config/hypr/hyprpaper.conf"
local borders_lua = home .. "/.config/hypr/conf/borders.lua"

local monitors = { "eDP-2", "DP-3", "DP-4", "DP-8", "DP-9", "DP-10" }
local fit_mode = "cover"

local active_colors = {
	["1"] = { colors = { "rgba(4ed5d3ee)", "rgba(074a77ee)" }, angle = 45 },
	["2"] = { colors = { "rgba(ffcaabee)", "rgba(d86373ee)" }, angle = 45 },
	["3"] = { colors = { "rgba(58b1e0ee)", "rgba(ffe3e7ee)" }, angle = 45 },
	["4"] = { colors = { "rgba(f79345ee)", "rgba(85556fee)" }, angle = 45 },
	["5"] = { colors = { "rgba(72cce8ee)", "rgba(81476Dee)" }, angle = 45 },
}

local inactive_colors = {
	["1"] = "rgba(595959aa)",
	["2"] = "rgba(595959aa)",
	["3"] = "rgba(595959aa)",
	["4"] = "rgba(595959aa)",
	["5"] = "rgba(595959aa)",
}

local function get_wallpaper_number()
	local file = io.open(hyprpaper_conf, "r")

	if not file then
		return nil, "Could not open file"
	end

	for line in file:lines() do
		-- Match:
		-- path = /home/{user}/Pictures/Wallpapers/wallpaper-X.jpg
		local number = line:match("^%s*path%s*=%s*/home/%w+/Pictures/Wallpapers/wallpaper%-(%d+)%.jpg%s*$")

		if number then
			file:close()
			return tonumber(number)
		end
	end

	file:close()
	return nil, "No wallpaper path found"
end

local function pick_new_wallpaper(current)
	local wallpapers = { 1, 2, 3, 4, 5 }
	table.remove(wallpapers, current)

	local randomIndex = math.random(1, #wallpapers)
	local randomWallpaper = wallpapers[randomIndex]

	return randomWallpaper
end

local function get_wallpaper_cfg_for_monitor(wallpaper, monitor)
	return string.format(
		[[wallpaper {
    monitor = %s
    path = %s
    fit_mode = %s
}

]],
		monitor,
		wallpaperdir .. string.format("/wallpaper-%s.jpg", wallpaper),
		fit_mode
	)
end

local function set_new_hyprpaper_cfg(wallpaper)
	local new_hyprpaper_cfg = "splash = false\n\n"

	for _, monitor in ipairs(monitors) do
		new_hyprpaper_cfg = new_hyprpaper_cfg .. get_wallpaper_cfg_for_monitor(wallpaper, monitor)
	end

	local file = io.open(hyprpaper_conf, "w")

	if file then
		file:write(new_hyprpaper_cfg)
		file:close()
	else
		io.stderr("Error: Could not open the Hyprpaper config file at: " .. hyprpaper_conf)
	end
end

local function set_borders(wallpaper)
	local key = tostring(wallpaper)
	local active = active_colors[key]
	local inactive = inactive_colors[key]
	local borders_cfg = string.format(
		[[-- Auto-generated by wallpaper.lua

hl.config({
	general = {
		col = {
			active_border = { colors = { %q, %q }, angle = %d },
			inactive_border = %q,
		},
	},
})
]],
		active.colors[1],
		active.colors[2],
		active.angle,
		inactive
	)

	local file = io.open(borders_lua, "w")

	if file then
		file:write(borders_cfg)
		file:close()
	else
		io.stderr("Error: Could not open the Hyprpaper config file at: " .. hyprpaper_conf)
	end
end

local function set_wallpaper()
	local current, err = get_wallpaper_number()
	if current then
		local new_wallpaper = pick_new_wallpaper(current)

		set_new_hyprpaper_cfg(new_wallpaper)
		set_borders(new_wallpaper)
	else
		io.stderr:write("Error: " .. err)
	end

	os.execute("pkill -x hyprpaper >/dev/null 2>&1 || true")
	os.execute("hyprpaper >/dev/null 2>&1 &")
end

local M = {}

M.set_wallpaper = set_wallpaper

return M
