math.randomseed(os.time())

local home = os.getenv("HOME")
local wallpaperdir = home .. "/Pictures/Wallpapers"
local hyprpaper_conf = home .. "/.config/hypr/hyprpaper.conf"
local borders_lua = home .. "/.config/hypr/conf/borders.lua"

local monitors = { "eDP-2", "DP-3", "DP-4", "DP-8", "DP-9", "DP-10" }
local fit_mode = "cover"

local active_colors = {
	["1"] = { colors = { "rgba(4ed5d3ee)", "rgba(074a77ee)" }, angle = 45 },
	["2"] = { colors = { "rgba(ffcaabee)", "rgba(d86373ee)" }, angle = 45 },
	["3"] = { colors = { "rgba(58b1e0ee)", "rgba(ffe3e7ee)" }, angle = 45 },
	["4"] = { colors = { "rgba(f79345ee)", "rgba(85556fee)" }, angle = 45 },
	["5"] = { colors = { "rgba(72cce8ee)", "rgba(81476Dee)" }, angle = 45 },
}

local inactive_colors = {
	["1"] = "rgba(595959aa)",
	["2"] = "rgba(595959aa)",
	["3"] = "rgba(595959aa)",
	["4"] = "rgba(595959aa)",
	["5"] = "rgba(595959aa)",
}

local function shell_quote(s)
	return "'" .. s:gsub("'", [['"'"']]) .. "'"
end

local function read_current_wallpaper()
	local f = io.open(hyprpaper_conf, "r")
	if not f then
		return ""
	end

	for line in f:lines() do
		local path = line:match("^%s*path%s*=%s*(.+)%s*$")
		if path then
			f:close()
			return path
		end
	end

	f:close()
	return ""
end

local function find_wallpapers()
	local cmd = "find " .. shell_quote(wallpaperdir) .. " -type f \\( -iname '*.jpg' -o -iname '*.png' \\) -print0"

	local p = io.popen(cmd, "r")
	if not p then
		error("Could not run find")
	end

	local output = p:read("*a")
	p:close()

	local files = {}
	for file in output:gmatch("([^%z]+)") do
		table.insert(files, file)
	end

	return files
end

local function pick_new_wallpaper(current)
	local files = find_wallpapers()

	if #files == 0 then
		io.stderr:write("Error: No wallpapers found in '" .. wallpaperdir .. "'.\n")
		os.exit(1)
	end

	local filtered = {}
	for _, file in ipairs(files) do
		if file ~= current then
			table.insert(filtered, file)
		end
	end

	if #filtered > 0 then
		files = filtered
	end

	return files[math.random(#files)]
end

local function write_file_atomically(path, contents)
	local dir = path:match("^(.*)/[^/]+$")
	local tmp = dir .. "/.tmp-" .. tostring(os.time()) .. "-" .. tostring(math.random(1000000))

	local f = assert(io.open(tmp, "w"))
	f:write(contents)
	f:close()

	assert(os.rename(tmp, path))
end

local function write_hyprpaper_conf(wallpaper)
	local lines = {}

	table.insert(lines, "splash = false\n")

	for _, monitor in ipairs(monitors) do
		table.insert(lines, "wallpaper {")
		table.insert(lines, "   monitor = " .. monitor)
		table.insert(lines, "   path = " .. wallpaper)
		table.insert(lines, "   fit_mode = " .. fit_mode)
		table.insert(lines, "}\n")
	end

	print(table.concat(lines, "\n"))
	write_file_atomically(hyprpaper_conf, table.concat(lines, "\n"))
end

local function write_borders_lua(num)
	local active = active_colors[num]
	-- print("active: " .. active)
	local inactive = inactive_colors[num]
	print("inactive: " .. inactive)

	if not active or not inactive then
		return false
	end

	hl.config({
		general = {
			col = {
				active_border = { colors = { active.colors[1], active.colors[2] }, angle = active.angle },
				inactive_border = inactive,
			},
		},
	})

	-- 	local contents = string.format(
	-- 		[[
	-- -- Auto-generated by random_wallpaper.lua
	-- hl.config({
	--     general = {
	--         col = {
	--             active_border = { colors = { %q, %q }, angle = %d },
	--             inactive_border = %q,
	--         },
	--     },
	-- })
	-- ]],
	-- 		active.colors[1],
	-- 		active.colors[2],
	-- 		active.angle,
	-- 		inactive
	-- 	)
	--
	-- 	write_file_atomically(borders_lua, contents)
	return true
end

function set_wallpaper()
	local current = read_current_wallpaper()
	print("Current: " .. current)
	local wallpaper = pick_new_wallpaper(current)
	print("Wallpaper: " .. wallpaper)

	local filename = wallpaper:match("([^/]+)$") or wallpaper
	print("filename: " .. filename)
	local wallpaper_num = filename:match("wallpaper%-(%d+)")
	print("wallpaper_num: " .. wallpaper_num)

	write_hyprpaper_conf(wallpaper)

	if wallpaper_num and write_borders_lua(wallpaper_num) then
		-- ok
	else
		io.stderr:write("Warning: No color scheme defined for wallpaper '" .. filename .. "'.\n")
	end

	-- os.execute("pkill -x hyprpaper >/dev/null 2>&1 || true")
	-- os.execute("hyprpaper >/dev/null 2>&1 &")
	-- os.execute("hyprctl reload")
end

set_wallpaper()
