-- Auto-generated by random_wallpaper.lua
hl.config({
    general = {
        col = {
            active_border = { colors = { "rgba(f79345ee)", "rgba(85556fee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})
